### PR TITLE
Adapt homepage, add documentation URL, use newest version

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- the repo has been moved to the pytest-dev organization

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

This PR supersedes the other currrently open PRs.

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
@conda-forge-admin please rerender

**Comment by hadim** [comment]
@mrbean-bremen do you want to add yourself as a maintainer?

**Comment by mrbean-bremen** [comment]
Sure, that would make sense!

**Comment by mrbean-bremen** [comment]
@hadim - I guess you have to request to add me as a maintainer, right? I'm not quite familiar with conda-forge yet.

**Comment by hadim** [comment]
Simply add yourself to the meta file of that PR at the very end and i will merge it.

**Comment by mrbean-bremen** [comment]
Thanks - sorry, I only just saw that the maintainer list is also there...

**Pull request merged**
